export const themePresets = [
    {
        name: 'Ocean Blue',
        slug: 'ocean-blue',
        primary: '#3b82f6',
        primaryLight: '#60a5fa',
        primaryDark: '#2563eb',
        accent: '#06b6d4',
        gradient: 'linear-gradient(135deg, #3b82f6, #06b6d4)',
        isDefault: true,
    },
    {
        name: 'Royal Purple',
        slug: 'royal-purple',
        primary: '#8b5cf6',
        primaryLight: '#a78bfa',
        primaryDark: '#7c3aed',
        accent: '#d946ef',
        gradient: 'linear-gradient(135deg, #8b5cf6, #d946ef)',
        isDefault: false,
    },
    {
        name: 'Forest Green',
        slug: 'forest-green',
        primary: '#10b981',
        primaryLight: '#34d399',
        primaryDark: '#059669',
        accent: '#14b8a6',
        gradient: 'linear-gradient(135deg, #10b981, #14b8a6)',
        isDefault: false,
    },
    {
        name: 'Rose Red',
        slug: 'rose-red',
        primary: '#f43f5e',
        primaryLight: '#fb7185',
        primaryDark: '#e11d48',
        accent: '#f97316',
        gradient: 'linear-gradient(135deg, #f43f5e, #f97316)',
        isDefault: false,
    },
    {
        name: 'Sunset Orange',
        slug: 'sunset-orange',
        primary: '#f97316',
        primaryLight: '#fb923c',
        primaryDark: '#ea580c',
        accent: '#eab308',
        gradient: 'linear-gradient(135deg, #f97316, #eab308)',
        isDefault: false,
    },
    {
        name: 'Teal',
        slug: 'teal',
        primary: '#14b8a6',
        primaryLight: '#2dd4bf',
        primaryDark: '#0d9488',
        accent: '#06b6d4',
        gradient: 'linear-gradient(135deg, #14b8a6, #06b6d4)',
        isDefault: false,
    },
    {
        name: 'Sakura Pink',
        slug: 'sakura-pink',
        primary: '#ec4899',
        primaryLight: '#f472b6',
        primaryDark: '#db2777',
        accent: '#a855f7',
        gradient: 'linear-gradient(135deg, #ec4899, #a855f7)',
        isDefault: false,
    },
    {
        name: 'Amber Gold',
        slug: 'amber-gold',
        primary: '#f59e0b',
        primaryLight: '#fbbf24',
        primaryDark: '#d97706',
        accent: '#ef4444',
        gradient: 'linear-gradient(135deg, #f59e0b, #ef4444)',
        isDefault: false,
    },
];
